version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Creating deployment package..."
      - zip -r deployment_package.zip index.js node_modules package.json buildspec.yml
      - echo "Build stage complete"
  post_build:
    commands:
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name stc-lambdaInvoke --zip-file fileb://deployment_package.zip
      - echo "DONE!!"

artifacts:
  files:
    - deployment_package.zip
